### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [Diablo-D3/config#1]
Hey, found this from a link you posted on HN.  I looked at your install script and I just thought I would suggest looking into Homesick (or the Bash version, which I use, Homeshick).  It takes care of all that for you.  For example, for me it would look something like this:
```sh
$ homeshick track main ~/.vimrc
$ ls -l ~/.vimrc
.vimrc -> /home/me/.homesick/repos/main/home/.vimrc
```
That moved the file to the "castle" (git repo) called "main" and replaced it with a symlink.  Then I can do something like:
```sh
$ homeshick cd main
$ git commit -m "Added .vimrc"
$ git push 
$ ssh me@othercomputer "homeshick pull -b"
```
That will commit the file, push the git repo to upstream, then ssh into my other computer, pull from the repo, and symlink all changes into place.  I have a cronjob to do the pulling automatically on my non-primary systems, so I don't have to keep them up-to-date manually.

Been using Homeshick for a few years now, and I highly recommend it.  I looked into several dotfile-managing solutions before settling on it, because it seems to be the most powerful and easiest to use.  Good documentation, too.

Anyway, hope you find this useful.  Cheers.

**Comment by Diablo-D3** [comment]
I'll have to look into that, thanks.
